# Generated by Django 5.2.1 on 2025-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('diseases', models.ManyToManyField(to='checker.disease')),
                ('symptoms', models.ManyToManyField(to='checker.symptom')),
            ],
        ),
    ]
